### ISSUE TITLE
change name of defclass block

### ISSUE THREAD

**Issue by xrme** [Clozure/ccldoc#10]
https://github.com/Clozure/ccldoc/blob/master/source/representation.lisp#L204

Since block is a symbol in the CL package, per http://www.lispworks.com/documentation/HyperSpec/Body/11_abab.htm, saying "(defclass block ...)" is undefined.

Instead of `block`, perhaps `text-block` or `blockquote` would be an alternative.  This would require updates to the output-xxx.lisp files and to `ccldoc.ccldoc`.

**Comment by KZiemian** [comment]
I will try understand and correct this working on documentation. But in this moment I don't have clear understanding if something more that changing of names need to be done.
