### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ghost** [Clozure/ccldoc#2]
There is no LICENSE or LICENSE.txt in the root of the repo. There are files which contains the license information inside, but there are also files without it. I think the LICENSE should be added?

**Comment by xrme** [comment]
Added LICENSE file (Apache License 2.0) and updated files with boilerplate.

See 91eba9192f7a49bbdec28b3485df18bc308fa9d6 and 29fba9db14729a5dd155af57d0c64bbd6dc67e78

Thanks.
