### ISSUE TITLE
load-to-ccldoc-form: source note map seems to be ignored

### ISSUE THREAD

**Issue by phoe** [Clozure/ccldoc#4]
https://github.com/Clozure/ccldoc/blob/master/source/toplevel.lisp#L40
This is where `*nx-source-note-map*` is declared, it is a dynamic binding.

https://github.com/Clozure/ccldoc/blob/master/source/toplevel.lisp#L46
This is where the map is updated.

Is it just me, or is the hashtable not accessed anywhere else in CCLDOC and therefore wasted?

**Comment by phoe** [comment]
Moved to https://trac.clozure.com/ccl/ticket/1424#ticket

**Comment by xrme** [comment]
GitHub is the best place for issues now.

`*nx-source-note-map*` is used to make M-. work on the forms that precede the document contents.  It's a nice-to-have thing, but it's not actually needed to process a ccldoc document.

**Comment by xrme** [comment]
@phoe I think you have this figured out now.
